services:
  api:
    container_name: api_62C
    image: oven/bun
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    working_dir: /app
    command: "/bin/sh -c 'bun i && bun start'"
    environment:
      - NODE_ENV=development
  db:
    container_name: db_62C
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db